services:
  - type: web
    name: lex-fridman-brief
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-pro-exp-03-25
    autoDeploy: true